// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQpcJy62LeTGnKqfXSyaHOjAPuGLE36X4',
    appId: '1:79554856810:web:c91baefee012afe5f88713',
    messagingSenderId: '79554856810',
    projectId: 'alumniapp-ffdd0',
    authDomain: 'alumniapp-ffdd0.firebaseapp.com',
    storageBucket: 'alumniapp-ffdd0.appspot.com',
    measurementId: 'G-8Y0PLRLD1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK5vRbcsnRfEQ6slA2Putwh3IlE5NEbr8',
    appId: '1:79554856810:android:475bb36bb7301f30f88713',
    messagingSenderId: '79554856810',
    projectId: 'alumniapp-ffdd0',
    storageBucket: 'alumniapp-ffdd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUS7k9fCN7siRAs6jXmiIWe4onHb1kxyo',
    appId: '1:79554856810:ios:f1e09eb0db0ce9a6f88713',
    messagingSenderId: '79554856810',
    projectId: 'alumniapp-ffdd0',
    storageBucket: 'alumniapp-ffdd0.appspot.com',
    iosBundleId: 'com.example.alumniApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQpcJy62LeTGnKqfXSyaHOjAPuGLE36X4',
    appId: '1:79554856810:web:ce30ff09a9475f26f88713',
    messagingSenderId: '79554856810',
    projectId: 'alumniapp-ffdd0',
    authDomain: 'alumniapp-ffdd0.firebaseapp.com',
    storageBucket: 'alumniapp-ffdd0.appspot.com',
    measurementId: 'G-085TEVFTPE',
  );
}
